import streamlit as st
import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from dashboard.components.ui import inject_custom_css, draw_status_bar

# Initialize settings
st.set_page_config(
    page_title="RF Knowledge Base - RF Spectrum Intelligence Platform",
    page_icon="📚",
    layout="wide"
)

inject_custom_css()
draw_status_bar(sdr_active=False, db_status="LOADED")

st.title("📚 RF Knowledge Base & Concepts")
st.markdown("Learn the fundamental engineering concepts behind Software Defined Radio (SDR) and digital signal processing (DSP).")

# Inject a beautiful mock CSS spectrum waterfall animation to wow the user!
st.markdown(
    """
    <style>
    @keyframes waterfall {
        0% { background-position: 0% 0%; }
        100% { background-position: 0% 100%; }
    }
    .waterfall-box {
        height: 120px;
        border: 1px solid #2D3748;
        border-radius: 6px;
        margin-bottom: 25px;
        /* Animated vertical matrix scan lines */
        background: linear-gradient(
            to bottom,
            rgba(14, 17, 23, 0.9) 0%,
            rgba(0, 240, 255, 0.4) 30%,
            rgba(179, 136, 255, 0.5) 50%,
            rgba(0, 230, 118, 0.3) 70%,
            rgba(14, 17, 23, 0.9) 100%
        );
        background-size: 100% 200%;
        animation: waterfall 4s linear infinite;
        position: relative;
        overflow: hidden;
    }
    .waterfall-overlay {
        position: absolute;
        top: 10px;
        left: 15px;
        font-family: 'JetBrains Mono', monospace;
        font-size: 12px;
        color: #00f0ff;
        text-shadow: 0 0 5px rgba(0, 240, 255, 0.8);
        background-color: rgba(14, 17, 23, 0.7);
        padding: 4px 8px;
        border-radius: 4px;
        border: 1px solid #00f0ff;
    }
    </style>
    <div class="waterfall-box">
        <div class="waterfall-overlay">MOCK SPECTROGRAM SCANNER: RUNNING</div>
    </div>
    """,
    unsafe_allow_html=True
)

# Tab interface for different categories
tab_basics, tab_protocols, tab_dsp = st.tabs([
    "📻 SDR Basics & Hardware", 
    "📡 Signals & Protocols (ADS-B, AIS, LoRa)", 
    "🧮 DSP & Math (IQ Data, FFT, Waterfalls)"
])

with tab_basics:
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("What is Software Defined Radio (SDR)?")
        st.write(
            """
            Traditionally, radio receivers relied heavily on hardware components (mixers, filters, amplifiers, and demodulators) 
            to isolate and decode analog waveforms. 
            
            **Software Defined Radio (SDR)** shifts this complexity from hardware to software. An SDR receiver:
            1. Down-converts high-frequency RF signals.
            2. Digits them using an Analog-to-Digital Converter (ADC).
            3. Streams the raw data samples (called **I/Q samples**) directly to a computer.
            
            Once the samples are in memory, software routines (written in C++ or Python) perform filtering, tuning, and demodulation. 
            This makes a single hardware device capable of receiving FM broadcast, tracking planes, and reading weather satellites simply by swapping the software script.
            """
        )
        
        st.subheader("Common SDR Hardware")
        st.markdown(
            """
            * **RTL-SDR (V3/V4)**: The most popular entry-level SDR. Based on the RTL2832U DVB-T dongle chip. Cost-effective (~$30) and covers 500 kHz to 1.7 GHz.
            * **HackRF One**: A half-duplex transceiver (can transmit and receive). Covers 1 MHz to 6 GHz.
            * **LimeSDR / PlutoSDR**: Full-duplex transceivers targeting cellular and MIMO prototyping.
            """
        )

    with col2:
        st.subheader("How SDR Down-conversion Works")
        st.markdown(
            """
            To capture high frequency waves (e.g. Wi-Fi at 2.4 GHz) using low-frequency processors, SDRs use a **Local Oscillator (LO)** and a **Mixer**. 
            
            By multiplying the incoming RF signal by a reference sine wave generated by the LO, the frequency is shifted downwards to baseband:
            
            $$\\text{Output Frequencies} = |f_{\\text{RF}} \\pm f_{\\text{LO}}|$$
            
            The low-frequency difference ($f_{\\text{RF}} - f_{\\text{LO}}$) is filtered out and sampled by the ADC. This central frequency is called the **Center Frequency**.
            """
        )
        
        st.info(
            "💡 **Did you know?** The RTL-SDR was originally designed as a cheap USB TV receiver dongle. In 2012, security researchers discovered that the raw digital samples could be accessed directly, sparking the modern SDR revolution."
        )

with tab_protocols:
    col3, col4 = st.columns(2)
    
    with col3:
        st.subheader("✈️ ADS-B (Aviation Transponders)")
        st.write(
            """
            **Automatic Dependent Surveillance-Broadcast (ADS-B)** is the global standard for tracking commercial aircraft. 
            
            * **Frequency**: 1090 MHz (Mode S transponder downlink).
            * **Modulation**: Pulse Position Modulation (PPM) at 1 Mbps.
            * **Structure**: Each transmission is a short, 120-microsecond burst. It starts with a 8-microsecond preamble followed by 112 bits of data containing aircraft ID, latitude, longitude, altitude, and heading.
            * **Range**: Line of sight (can exceed 250 miles with a basic antenna).
            """
        )
        
        st.subheader("🚢 AIS (Maritime Tracking)")
        st.write(
            """
            The **Automatic Identification System (AIS)** is the maritime equivalent of ADS-B, used to monitor commercial vessels.
            
            * **Frequencies**: 161.975 MHz (Channel 87B) and 162.025 MHz (Channel 88B).
            * **Modulation**: Gaussian Minimum Shift Keying (GMSK) at 9600 bps.
            * **Access Method**: Self-Organizing Time Division Multiple Access (SOTDMA). Ships synchronize time slots using GPS to broadcast data without collision.
            """
        )

    with col4:
        st.subheader("📶 LoRa & ISM Bands")
        st.write(
            """
            **LoRa (Long Range)** is a proprietary spread spectrum modulation technique designed for IoT sensors and low-power telemetry.
            
            * **Frequencies**: Unlicensed Industrial, Scientific, and Medical (ISM) bands (433 MHz, 868 MHz, 915 MHz).
            * **Modulation**: **Chirp Spread Spectrum (CSS)**. Instead of modulating frequency or phase in steps, LoRa uses continuous linear frequency sweeps (chirps) over a bandwidth.
            * **Why CSS?** Chirps are highly immune to noise, multipath fading, and Doppler shift, enabling communication deep below the noise floor using nanowatts of power.
            """
        )

with tab_dsp:
    col5, col6 = st.columns(2)
    
    with col5:
        st.subheader("🌊 Understanding IQ Data")
        st.write(
            """
            Raw RF waves are sinusoidal, having instantaneous amplitude, frequency, and phase. Sampling a signal on a single wire only captures amplitude over time. 
            To preserve phase information, SDRs split the signal into two components:
            
            1. **In-Phase (I)**: The signal multiplied by a cosine wave.
            2. **Quadrature (Q)**: The signal multiplied by a sine wave (shifted by $90^\\circ$).
            
            We express IQ samples mathematically as complex numbers:
            
            $$s(t) = I(t) + jQ(t)$$
            
            This allows us to calculate:
            * **Instantaneous Power (Amplitude)**: $A = \\sqrt{I^2 + Q^2}$
            * **Instantaneous Phase**: $\\theta = \\text{arctan2}(Q, I)$
            """
        )
        
        st.subheader("🧪 What is a Waterfall Spectrogram?")
        st.write(
            """
            A **Waterfall display** is a visual representation of the radio spectrum over time.
            * The **X-axis** represents frequency.
            * The **Y-axis** represents time flowing downwards.
            * The **Color intensity** represents the power spectral density (strength) of the signal.
            
            Waterfalls are incredibly useful because they show temporal patterns (e.g. constant carriers vs. short periodic packets vs. sweeping LoRa chirps).
            """
        )

    with col6:
        st.subheader("🧮 The Fast Fourier Transform (FFT)")
        st.write(
            """
            An SDR streams raw time-domain IQ samples (how amplitude changes over time). However, RF engineers want to know how power is distributed across different frequencies.
            
            The **Fourier Transform** is the mathematical bridge that converts time-domain signals into the frequency domain. 
            The **Fast Fourier Transform (FFT)** is an optimized algorithm that computes this conversion in real-time:
            
            $$X(f) = \\sum_{n=0}^{N-1} x(n) e^{-j 2 \\pi f n / N}$$
            
            The output of the FFT is a complex array. Taking the squared magnitude of this array yields the power at each frequency bin, which is plotted as the Spectrum Analyzer graph.
            """
        )
        
        # Display math example
        st.markdown("**FFT Windowing:**")
        st.write(
            """
            To calculate FFTs on continuous streams, we divide the data into segments (windows). 
            Applying a windowing function (such as Hanning or Hamming) to each segment prevents sharp discontinuities at the segment boundaries, reducing spectral leakage (smearing of frequencies).
            """
        )
